service: filter

plugins:
  - serverless-webpack
  - serverless-plugin-aws-alerts

provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/TelegramUserFilters'

functions:
  deleteFilter:
    handler: delete-filter.handler
    timeout: 10
  updateFilter:
    handler: update-filter.handler
    timeout: 10
  createFilter:
    handler: create-filter.handler
    timeout: 10
  queryFilter:
    handler: query-filter.handler
    timeout: 10

custom:
  accountId: '${env:AWS_ACCOUNT_ID}'
  webpack: ${file(../../serverless/globals.yml):webpack}
  alerts: ${file(../../serverless/globals.yml):alerts}

# Modes for config validation. The default is warn.
# `error` throws an exception,
# `warn` logs error to console,
# `off` disables validation at all.
configValidationMode: error
